In [1]:
def fizzbuzz():
    for i in range(1,101):
        
        # Condition checks to modify i
        modifier = ''
        if i % 3 == 0:
            modifier += 'fizz'
        if i % 5 == 0:
            modifier += 'buzz'
        if i % 7 == 0:
            modifier += 'fuzz'
        if i % 9 == 0:
            modifier += 'bizz'
        
        # If all checks are false print i
        if modifier == '':
            print(i)
        # Otherwise print the modified statement
        else:
            print(modifier)
            
def fizzbuzzlistcomp():
    fizzbuzz = [
                # Replace with text if no remainder
                "fizz"*(not i%3) + "buzz"*(not i%5) +
                "fuzz"*(not i%7) + "bizz"*(not i%9) +
                "zuzz"*(not i%33) + "zizz"*(not i%55) +
                "mizz"*(not i%77) + "muzz"*(not i%99)
                # Otherwise return the integer if string is empty
                or str(i)
                # Iterate over 1 to 100
                for i in range(1, 101)
                # Choose what to keep
                if i % 1 == 0
                if 50 < i < 77
    ]
    return fizzbuzz

if __name__ == '__main__':
    #fizzbuzz()
    fizzbuzz = fizzbuzzlistcomp()
    print('\n'.join(fizzbuzz))



fizz
52
53
fizzbizz
buzzzizz
fuzz
fizz
58
59
fizzbuzz
61
62
fizzfuzzbizz
64
buzz
fizzzuzz
67
68
fizz
buzzfuzz
71
fizzbizz
73
74
fizzbuzz
76


## Question 1
Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included). The numbers obtained should be printed in a comma-separated sequence on a single line.

In [42]:
def q1():
    output = [
              str(i)#*(not i%7)
              for i in range(2000, 3201)
              if i % 7 == 0
              if i % 5 != 0
    ]
    print(', '.join(output))
    
q1()

2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199


## Question 2
Question: Write a program which can compute the factorial of a given numbers. The results should be printed in a comma-separated sequence on a single line. Suppose the following input is supplied to the program: 8 Then, the output should be: 40320

In [43]:
def fact(x):
    if x==0:
        return 1
    return x * fact(x - 1)

fact(8)

40320

## Question 3
Question: With a given integral number n, write a program to generate a dictionary that contains (i, i*i) such that is an integral number between 1 and n (both included). and then the program should print the dictionary. Suppose the following input is supplied to the program: 8 Then, the output should be: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}

In [2]:
def q3(x):
    return {x:x*x for x in range(1, x+1)}
q3(8)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}

## Question 4
Question: Write a program which accepts a sequence of comma-separated numbers from console and generate a list and a tuple which contains every number. Suppose the following input is supplied to the program: 34,67,55,33,12,98 Then, the output should be: ['34', '67', '55', '33', '12', '98'] ('34', '67', '55', '33', '12', '98')

In [3]:
def q4():
    x = input().split(',')
    return x, tuple(x)
q4()

(['34', '67', '55', '33', '12', '98'], ('34', '67', '55', '33', '12', '98'))

## Question 5
Question: Define a class which has at least two methods: getString: to get a string from console input printString: to print the string in upper case. Also please include simple test function to test the class methods.

In [4]:
class String:
    def __init__(self):
        self.s = ''
    
    def getString(self):
        self.s = input()
        
    def printString(self):
        print(self.s.upper())
        
strObj = String()
strObj.getString()
strObj.printString()

HELLO


## Question 6 
Write a program that calculates and prints the value according to the given formula: Q = Square root of [(2 * C * D)/H] Following are the fixed values of C and H: C is 50. H is 30. D is the variable whose values should be input to your program in a comma-separated sequence. Example Let us assume the following comma separated input sequence is given to the program: 100,150,180 The output of the program should be: 18,22,24

In [5]:
import numpy as np
def q6():
    allD = [int(i) for i in input().split(',')]
    D = np.array(allD)
    C  = 50
    H = 30
    Q = np.sqrt((2 * C * D)/H).astype(int).astype(str)
    print(','.join(Q))

q6()

8


## Question 7
Question: Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j. Note: i=0,1.., X-1; j=0,1,¡­Y-1. Example Suppose the following inputs are given to the program: 3,5 Then, the output of the program should be: [[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]

In [7]:
def q7(X, Y):
    arr = np.zeros([X, Y]).astype(int)
    arr[1] = range(0, Y)
    arr[2] = range(0, 2*Y, 2)
    print(arr)
q7(3,5)

# alt

input_str = input()
dimensions=[int(x) for x in input_str.split(',')]
rowNum=dimensions[0]
colNum=dimensions[1]
multilist = [[0 for col in range(colNum)] for row in range(rowNum)]

for row in range(rowNum):
    for col in range(colNum):
        multilist[row][col]= row*col

print(multilist)

[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]
[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]


## Question 8
Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically. Suppose the following input is supplied to the program: without,hello,bag,world Then, the output should be: bag,hello,without,world



In [8]:
def q8():
    words = [word for word in input().split(',')]
    words.sort()
    print(','.join(words))
    
q8()
    

bag,hello,without,world


## Question 9
 Write a program that accepts sequence of lines as input and prints the lines after making all characters in the sentence capitalized. Suppose the following input is supplied to the program: Hello world Practice makes perfect Then, the output should be: HELLO WORLD PRACTICE MAKES PERFECT

In [ ]:
def q9():
    lines = [line for line in input().split()]

In [ ]:
def solution(lst):
	# Write your solution here.
	ages = []
	for i in range(len(lst)):
		dct = lst[i]
		ages.append(dct['age']) 
	oldest = max(ages)
	person = next(item for item in lst if item["age"] == oldest)
	return person

lst = [
    {"name": "james", "age": 26},
    {"name": "ravi", "age": 50},
    {"name": "john", "age": 50}
]
solution(lst)

{'name': 'ravi', 'age': 50}

In [ ]:
from collections import defaultdict

def group_by_owners(files):
    reverse_files = defaultdict(list)
    {reverse_files[v].append(k) for k, v in files.items()}
    result = dict(reverse_files)
    return result

files = {
        'Input.txt': 'Randy',
        'Code.py': 'Stan',
        'Output.txt': 'Randy'
    }   
group_by_owners(files)

{'Randy': ['Input.txt', 'Output.txt'], 'Stan': ['Code.py']}

In [ ]:
class Node:
    def __init__(self, value):
        self.value = value
        self.left = None
        self.right = None
        
        

class BinaryTree:
    def __init__(self, root):
        self.root = Node(root)
        
    
    def print_tree(self, traversal_type):
        if traversal_type == 'preorder':
            return self.preorder_print(tree.root, '')
        elif traversal_type == 'inorder':
            return self.inorder_print(tree.root, '')
        elif traversal_type == 'postorder':
            return self.postorder_print(tree.root, '')
        else:
            print(f'Traversal type ' + str(traversal_type) + ' is not supported.')
            
        
    def preorder_print(self, start, traversal):
        '''
        root -> left -> right
        '''
        if start:
            traversal += (str(start.value) + '-')
            traversal = self.preorder_print(start.left, traversal)
            traversal = self.preorder_print(start.right, traversal)
        return traversal
    
    
    def inorder_print(self, start, traversal):
        '''
        left -> root -> right
        '''
        if start:
            traversal = self.preorder_print(start.left, traversal)
            traversal += (str(start.value) + '-')
            traversal = self.preorder_print(start.right, traversal)
        return traversal
    
    
    def postorder_print(self, start, traversal):
        '''
        left -> right -> root
        '''
        if start:
            traversal = self.preorder_print(start.left, traversal)
            traversal = self.preorder_print(start.right, traversal)
            traversal += (str(start.value) + '-')
        return traversal
    
    
    def treeSum(self, root):
        '''
        Sums all the values in a binary tree.
        '''
        if root is None:
            return 0
        else:
            leftSum = self.treeSum(root.left)
            rightSum = self.treeSum(root.right)
            return root.value + leftSum + rightSum
    
    
    def reverseTree(self, root):
        '''
        Reverses a binary tree.
        '''
        if root is None:
            return
        else:
            self.reverseTree(root.left)
            self.reverseTree(root.right)
            root.left, root.right = root.right, root.left
            
            
            
        
tree = BinaryTree(1)
tree.root.left = Node(2)
tree.root.right = Node(3)
tree.root.left.left = Node(4)
tree.root.right.right = Node(5)

tree.reverseTree(tree.root)

tree.treeSum(tree.root)

tree.print_tree('preorder')

'1-3-5-2-4-'